USE [LearnersAcademyDB]
GO

/****** Object:  Table [dbo].[CLASSES]    Script Date: 8/31/2020 4:29:37 PM ******/
DROP TABLE [dbo].[CLASSES]
GO

/****** Object:  Table [dbo].[CLASSES]    Script Date: 8/31/2020 4:29:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLASSES](
	[CLASS_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLASS_NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[CLASS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


