USE [LearnersAcademyDB]
GO

/****** Object:  Table [dbo].[LOGIN_USERS]    Script Date: 8/31/2020 4:29:44 PM ******/
DROP TABLE [dbo].[LOGIN_USERS]
GO

/****** Object:  Table [dbo].[LOGIN_USERS]    Script Date: 8/31/2020 4:29:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOGIN_USERS](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[PASSWORD] [varchar](255) NULL,
	[ROLE] [varchar](255) NULL,
	[USER_NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


