USE [LearnersAcademyDB]
GO

ALTER TABLE [dbo].[STUDENTS] DROP CONSTRAINT [FKrfiplnidulx9742da7b4chshy]
GO

/****** Object:  Table [dbo].[STUDENTS]    Script Date: 8/31/2020 4:29:50 PM ******/
DROP TABLE [dbo].[STUDENTS]
GO

/****** Object:  Table [dbo].[STUDENTS]    Script Date: 8/31/2020 4:29:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STUDENTS](
	[STUDENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL_ADDRESS] [varchar](255) NULL,
	[FIRST_NAME] [varchar](255) NULL,
	[LAST_NAME] [varchar](255) NULL,
	[PHONE_NUMBER] [varchar](255) NULL,
	[CLASS_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[STUDENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STUDENTS]  WITH CHECK ADD  CONSTRAINT [FKrfiplnidulx9742da7b4chshy] FOREIGN KEY([CLASS_ID])
REFERENCES [dbo].[CLASSES] ([CLASS_ID])
GO

ALTER TABLE [dbo].[STUDENTS] CHECK CONSTRAINT [FKrfiplnidulx9742da7b4chshy]
GO


