USE [LearnersAcademyDB]
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES] DROP CONSTRAINT [FKqu0pxqel47unm3q8n2guypmrc]
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES] DROP CONSTRAINT [FKbla048u84qbs5khpnd1uxdd3l]
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES] DROP CONSTRAINT [FKauoks8gs73fbhywvolxlj2vkd]
GO

/****** Object:  Table [dbo].[SUBJECTS_CLASSES]    Script Date: 8/31/2020 4:30:02 PM ******/
DROP TABLE [dbo].[SUBJECTS_CLASSES]
GO

/****** Object:  Table [dbo].[SUBJECTS_CLASSES]    Script Date: 8/31/2020 4:30:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SUBJECTS_CLASSES](
	[SUBJECT_CLASS_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLASS_ID] [int] NULL,
	[SUBJECT_ID] [int] NULL,
	[TEACHER_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SUBJECT_CLASS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES]  WITH CHECK ADD  CONSTRAINT [FKauoks8gs73fbhywvolxlj2vkd] FOREIGN KEY([CLASS_ID])
REFERENCES [dbo].[CLASSES] ([CLASS_ID])
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES] CHECK CONSTRAINT [FKauoks8gs73fbhywvolxlj2vkd]
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES]  WITH CHECK ADD  CONSTRAINT [FKbla048u84qbs5khpnd1uxdd3l] FOREIGN KEY([SUBJECT_ID])
REFERENCES [dbo].[SUBJECTS] ([SUBJECT_ID])
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES] CHECK CONSTRAINT [FKbla048u84qbs5khpnd1uxdd3l]
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES]  WITH CHECK ADD  CONSTRAINT [FKqu0pxqel47unm3q8n2guypmrc] FOREIGN KEY([TEACHER_ID])
REFERENCES [dbo].[TEACHERS] ([TEACHER_ID])
GO

ALTER TABLE [dbo].[SUBJECTS_CLASSES] CHECK CONSTRAINT [FKqu0pxqel47unm3q8n2guypmrc]
GO


