USE [LearnersAcademyDB]
GO

/****** Object:  Table [dbo].[SUBJECTS]    Script Date: 8/31/2020 4:29:56 PM ******/
DROP TABLE [dbo].[SUBJECTS]
GO

/****** Object:  Table [dbo].[SUBJECTS]    Script Date: 8/31/2020 4:29:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SUBJECTS](
	[SUBJECT_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBJECT_NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SUBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


