USE [LearnersAcademyDB]
GO

/****** Object:  Table [dbo].[TEACHERS]    Script Date: 8/31/2020 4:30:06 PM ******/
DROP TABLE [dbo].[TEACHERS]
GO

/****** Object:  Table [dbo].[TEACHERS]    Script Date: 8/31/2020 4:30:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEACHERS](
	[TEACHER_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL_ADDRESS] [varchar](255) NULL,
	[FIRST_NAME] [varchar](255) NULL,
	[LAST_NAME] [varchar](255) NULL,
	[PHONE_NUMBER] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[TEACHER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


